#!/bin/bash
#  ██                       
# ░██                       
# ░██       ██████   ██████ 
# ░██████  ░░░░░░██ ░░██░░█ 
# ░██░░░██  ███████  ░██ ░  
# ░██  ░██ ██░░░░██  ░██    
# ░██████ ░░████████░███    
# ░░░░░    ░░░░░░░░ ░░░     
# nxll <nxll@taknik.io>

#RESTART
pkill lemonbar

#COLORS
fg="#B8B9B4"
bg="#21211F"

nblk="#262624"
bblk="#282826"
nred="#939490"
bred="#989995"
ngrn="#9AC70E"
bgrn="#C2FA11"
nylw="#B6B8B3"
bylw="#BBBDB8"
nblu="#727370"
bblu="#777875"
nmag="#D1D1CB"
bmag="#D6D6D0"
ncyn="#636361"
bcyn="#696966"
nwht="#AAABA6"
bwht="#AFB0AB"

#VARS
font="-jmk-neep-medium-r-semicondensed--11-100-75-75-c-50-iso8859-1"
glyph="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
height=18
border=5
muslength=45
#actchar="+"
#selchar="+"
#actchar=""
#selchar=""

if pgrep herbstluftwm; then
monitor=${1:-0}
bh=$(( $height + ($border * 2)))
herbstclient pad $monitor $bh
fi

WRK()
{
	wrkspce=$(xprop -root _NET_CURRENT_DESKTOP | sed -e 's/_NET_CURRENT_DESKTOP(CARDINAL) = //')
	
	if [ "${wrkspce}" = "0" ] ;
	then 
		echo "%{B$ngrn} %{F$bg}0%{F-} %{B$nblk} 1 2 3 4 %{B-}"
	elif [ "${wrkspce}" = "1" ] ;
	then
		echo "%{B$nblk} 0 %{B$ngrn} %{F$bg}1%{F-} %{B$nblk} 2 3 4 %{B-}"
	elif [ "${wrkspce}" = "2" ] ;
	then 
		echo "%{B$nblk} 0 1 %{B$ngrn} %{F$bg}2%{F-} %{B$nblk} 3 4 %{B-}"
	elif [ "${wrkspce}" = "3" ] ;
	then 
		echo "%{B$nblk} 0 1 2 %{B$ngrn} %{F$bg}3%{F-} %{B$nblk} 4 %{B-}"
	elif [ "${wrkspce}" = "4" ] ;
	then 
		echo "%{B$nblk} 0 1 2 3 %{B$ngrn} %{F$bg}4%{F-} %{B-}"
    else
		echo "%{B$ngrn} %{F$bg}NONE%{F-} %{B-}"
	fi
}

WIN()
{
    #echo -n "%{B$ngrn}%{F$bg}  %{F-}%{B-}"
	echo -n "%{B$bblk}%{F$fg} $(wname $(pfw)) %{F-}%{B-}"
}

MUSIC()
{
	playing=$(mpc status | sed -n 2p | cut -c1-9)
	
		if [ "${playing}" = "[playing]" ]; then
        	symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} $(mpc current -f "%artist% - %title%" | cut -c1-$muslength) %{B-}"
		elif [ ${playing} = "[paused]" ]; then
			symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} $(mpc current -f "%artist% - %title%" | cut -c1-$muslength) %{B-}"
		elif [ ! "${playing}" = "[playing]" ]; then
			symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} ··· %{B-}"
		fi

    echo -n "${symbol}${song}"
}

VOL()
{
	getvol=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1  )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
	
	echo -n "%{B$bblk}  %{B$nblk} $getvol% %{B-}"
}

BAT()
{
    percent=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

    if test $status = "Charging"; then
        symbol=""
        echo -n "%{B$bblk} ${symbol} %{B-}"
    elif test $status = "Full"; then
        symbol=""
        echo -n "%{B$bblk} ${symbol} %{B-}"
    else
        if test $percent -gt 66; then
            symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        elif test $percent -gt 34; then
            symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        else
		symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        fi
    fi

	echo -e "%{B$nblk} $percent% %{B-}"
}

NET()
{
	symbol="%{B$bblk}  %{B-}"
	disconnected=$(iw wls1 link | awk '/Not/ {print $1}')

	ssid=$(
	if [ "$disconnected" = "Not" ]; then
		echo "NOT CONNECTED"
	else
		iw wls1 link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//'
	fi)

	echo -n "${symbol}%{B$nblk} ${ssid} %{B-}"
}

DATE()
{
    echo -n "%{B$bblk} %{F$fg}$(date "+%d/%m " | tr [A-Z] [a-z])%{F-}%{B-}"
}

CLOCK()
{
    echo -n "%{B$ngrn}%{F$bg} $(date "+%H:%M") %{F-}%{B-}"
}

BAR()
{ 
    #ADD ALL THE THINGS
    while true; do
		buf="$(WRK) $(MUSIC)%{c}%{r}$(VOL) $(BAT) $(NET) $(DATE) $(CLOCK)" 
		echo "$buf"	
        sleep 0.1
    done | lemonbar -f $glyph \
        -f "$font" \
        -F "$fg" \
        -B "$bg" \
        -u "$border" \
		-r "$border" \
		-R "$bg" \
        -g "1270x$height+0+0" | sh &
}

BAR > /dev/null
