#!/bin/bash
#  ██                       
# ░██                       
# ░██       ██████   ██████ 
# ░██████  ░░░░░░██ ░░██░░█ 
# ░██░░░██  ███████  ░██ ░  
# ░██  ░██ ██░░░░██  ░██    
# ░██████ ░░████████░███    
# ░░░░░    ░░░░░░░░ ░░░     
# BARSCRIPT
# nxll <nxll@taknik.io>

#RESTART
pkill lemonbar

#COLORS
FG="#DCDCDC"
BG="#2A2F36"

NBLACK="#323740"
BBLACK="#3A404A"
NRED="#F6887A"
BRED="#FF8D7E"
NGREEN="#84CDC9"
BGREEN="#8AD6D2"
NYELLOW="#B0ACA9"
BYELLOW="#BAB6B3"
NBLUE="#729597"
BBLUE="#799FA1"
NPURPLE="#908A8A"
BPURPLE="#999393"
NCYAN="#AAC3C8"
BCYAN="#B2CCD1"
NWHITE="#F5F5F5"
BWHITE="#FFFFFF"

#VARS
FONT="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"
GLYPH="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
HEIGHT=18
BORDER=5
MUSLENGTH=45
#ACTCHAR="+"
#SELCHAR="+"
#ACTCHAR=""
#SELCHAR=""

if pgrep herbstluftwm; then
monitor=${1:-0}
herbstclient pad $monitor 24
fi

WRK()
{
	OGWKSPACE=$(xprop -root _NET_CURRENT_DESKTOP | sed -e 's/_NET_CURRENT_DESKTOP(CARDINAL) = //')
	
	if [ ${OGWKSPACE} = "0" ] ;
	then 
		echo "%{B$NGREEN} %{F$BG}0%{F-} %{B$NBLACK} 1 2 3 4 %{B-}"
	elif [ ${OGWKSPACE} = "1" ] ;
	then
		echo "%{B$NBLACK} 0 %{B$NGREEN} %{F$BG}1%{F-} %{B$NBLACK} 2 3 4 %{B-}"
	elif [ ${OGWKSPACE} = "2" ] ;
	then 
		echo "%{B$NBLACK} 0 1 %{B$NGREEN} %{F$BG}2%{F-} %{B$NBLACK} 3 4 %{B-}"
	elif [ ${OGWKSPACE} = "3" ] ;
	then 
		echo "%{B$NBLACK} 0 1 2 %{B$NGREEN} %{F$BG}3%{F-} %{B$NBLACK} 4 %{B-}"
	elif [ ${OGWKSPACE} = "4" ] ;
	then 
		echo "%{B$NBLACK} 0 1 2 3 %{B$NGREEN} %{F$BG}4%{F-} %{B-}"
    else
		echo "%{B$NGREEN} %{F$BG}ERROR%{F-} %{B-}"
	fi
}

WIN()
{
    #echo -n "%{B$NGREEN}%{F$BG}  %{F-}%{B-}"
	echo -n "%{B$BBLACK}%{F$FG} $(wname $(pfw)) %{F-}%{B-}"
}

MUSIC()
{
	PLAYING=$(mpc status | sed -n 2p | cut -c1-9)
	
		if [ "$PLAYING" = "[playing]" ] ; then
        	SYMBOL="%{B$BBLACK} %{F$FG}%{F-} %{B-}"
			SONG="%{B$NBLACK} $(mpc current -f "%artist% - %title%" | cut -c1-$MUSLENGTH) %{B-}"
		elif [ $PLAYING = "[paused]" ] ; then
			SYMBOL="%{B$BBLACK} %{F$FG}%{F-} %{B-}"
			SONG="%{B$NBLACK} $(mpc current -f "%artist% - %title%" | cut -c1-$MUSLENGTH) %{B-}"
		elif [ ! "$PLAYING" = "[playing]" ]; then
			SYMBOL="%{B$BBLACK} %{F$FG}%{F-} %{B-}"
			SONG="%{B$NBLACK} --- %{B-}"
		fi

    echo -n "${SYMBOL}${SONG}"
}

VOL()
{
	GETVOL=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1  )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
	
	echo -n "%{B$BBLACK}  %{B$NBLACK} $GETVOL% %{B-}"
}

BAT()
{
    percent=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

    if test $status = "Charging"; then
        symbol=""
        echo -n "%{B$BBLACK} ${symbol} %{B-}"
    elif test $status = "Full"; then
        symbol=""
        echo -n "%{B$BBLACK} ${symbol} %{B-}"
    else
        if test $percent -gt 66; then
            symbol=""
            echo -n "%{B$BBLACK} ${symbol} %{B-}"
        elif test $percent -gt 34; then
            symbol=""
            echo -n "%{B$BBLACK} ${symbol} %{B-}"
        else
		symbol=""
            echo -n "%{B$BBLACK} ${symbol} %{B-}"
        fi
    fi

	echo -e "%{B$NBLACK} $percent% %{B-}"
}

NET()
{
	SYMBOL="%{B$BBLACK}  %{B-}"
	WIFI_SSID=$(
	if [ grep -q "Not connected."] ; then
		echo "No AP"
	else
		iw wls1 link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//'
	fi)

	echo -n "${SYMBOL}%{B$NBLACK} ${WIFI_SSID} %{B-}"
}

DATE()
{
    echo -n "%{B$BBLACK} %{F$FG}$(date "+%d/%m " | tr [A-Z] [a-z])%{F-}%{B-}"
}

CLOCK()
{
    echo -n "%{B$NGREEN}%{F$BG} $(date "+%H:%M") %{F-}%{B-}"
}

BAR()
{ 
    #ADD ALL THE THINGS
    while true; do
		BUF="$(WRK) $(MUSIC)%{c}%{r}$(VOL) $(BAT) $(NET) $(DATE) $(CLOCK)" 
		echo $BUF	
        sleep 0.1
    done | lemonbar -f $GLYPH \
        -f $FONT \
        -F $FG \
        -B $BG \
        -u $BORDER \
		-r $BORDER \
		-R $BG \
        -g 1270x$HEIGHT+0+0 | sh &
}

BAR > /dev/null
