#!/bin/bash
#  ██                       
# ░██                       
# ░██       ██████   ██████ 
# ░██████  ░░░░░░██ ░░██░░█ 
# ░██░░░██  ███████  ░██ ░  
# ░██  ░██ ██░░░░██  ░██    
# ░██████ ░░████████░███    
# ░░░░░    ░░░░░░░░ ░░░     
# nxll <nxll@taknik.io>

#RESTART
pkill lemonbar

#COLORS
fg="#F2F3F5"
bg="#242529"

hint="#FB546E"
nblk="#2E2E33"
bblk="#37373D"
nred="#FA536D"
bred="#FF556F"
ngrn="#E66C7F"
bgrn="#FF788D"
nylw="#C3C5CC"
bylw="#D6D9E0"
nblu="#E5E5E5"
bblu="#F5F5F5"
nmag="#D6D6D6"
bmag="#EBEBEB"
ncyn="#E1E2E4"
bcyn="#E8E9EB"
nwht="#EFF0F2"
bwht="#FCFDFF"

#VARS
font="-uw-ttyp0-medium-r-normal--13-120-75-75-c-70-iso10646-1"
glyph="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
height=18
border=8
muslength=60
interface=wls1
#actchar="+"
#selchar="+"
#actchar=""
#selchar=""

if pgrep herbstluftwm; then
	monitor=${1:-0}
	bh=$(( $height + ($border * 2)))
	herbstclient pad $monitor $bh
fi

WRKL() {
	wrkspce=$(xprop -root _NET_CURRENT_DESKTOP | sed -e 's/_NET_CURRENT_DESKTOP(CARDINAL) = //')
	
	if [ "${wrkspce}" = "0" ] ;
	then 
		echo "%{B$hint} %{F$bg}000%{F-} %{B$nblk} 001 010 011 100 %{B-}"
	elif [ "${wrkspce}" = "1" ] ;
	then
		echo "%{B$nblk} 000 %{B$hint} %{F$bg}001%{F-} %{B$nblk} 010 011 100 %{B-}"
	elif [ "${wrkspce}" = "2" ] ;
	then 
		echo "%{B$nblk} 000 001 %{B$hint} %{F$bg}010%{F-} %{B$nblk} 011 100 %{B-}"
	elif [ "${wrkspce}" = "3" ] ;
	then 
		echo "%{B$nblk} 000 001 010 %{B$hint} %{F$bg}011%{F-} %{B$nblk} 100 %{B-}"
	elif [ "${wrkspce}" = "4" ] ;
	then 
		echo "%{B$nblk} 000 001 010 011 %{B$hint} %{F$bg}100%{F-} %{B-}"
    else
		echo "%{B$hint} %{F$bg}NONE%{F-} %{B-}"
	fi
}

WRK() {
	wrkspce=$(xprop -root _NET_CURRENT_DESKTOP | sed -e 's/_NET_CURRENT_DESKTOP(CARDINAL) = //')
	
	if [ "${wrkspce}" = "0" ] ;
	then 
		echo "%{B$hint} %{F$bg}0:0%{F-} %{B-}"
	elif [ "${wrkspce}" = "1" ] ;
	then
		echo "%{B$hint} %{F$bg}0:1%{F-} %{B-}"
	elif [ "${wrkspce}" = "2" ] ;
	then 
		echo "%{B$hint} %{F$bg}0:2%{F-} %{B-}"
	elif [ "${wrkspce}" = "3" ] ;
	then 
		echo "%{B$hint} %{F$bg}0:3%{F-} %{B-}"
	elif [ "${wrkspce}" = "4" ] ;
	then 
		echo "%{B$hint} %{F$bg}0:4%{F-} %{B-}"
    else
		echo "%{B$hint} %{F$bg}NONE%{F-} %{B-}"
	fi
}

WIN() {
    #echo -n "%{B$hint}%{F$bg}  %{F-}%{B-}"
	echo -n "%{B$bblk}%{F$fg} $(wname $(pfw)) %{F-}%{B-}"
}

MUSIC() {
	playing=$(mpc status | sed -n 2p | cut -c1-9)
	
		if [ "${playing}" = "[playing]" ]; then
        	symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} $(mpc current -f "%artist% - %title%" | cut -c1-$muslength) %{B-}"
		elif [ ${playing} = "[paused]" ]; then
			symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} $(mpc current -f "%artist% - %title%" | cut -c1-$muslength) %{B-}"
		elif [ ! "${playing}" = "[playing]" ]; then
			symbol="%{B$bblk} %{F$fg}%{F-} %{B-}"
			song="%{B$nblk} ··· %{B-}"
		fi

    echo -n "${symbol}${song}"
}

VOL() {
	getvol=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1  )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
	
	echo -n "%{B$bblk}  %{B$nblk} $getvol% %{B-}"
}

BAT() {
    percent=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

    if test $status = "Charging"; then
        symbol=""
        echo -n "%{B$bblk} ${symbol} %{B-}"
    elif test $status = "Full"; then
        symbol=""
        echo -n "%{B$bblk} ${symbol} %{B-}"
    else
        if test $percent -gt 66; then
            symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        elif test $percent -gt 34; then
            symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        else
		symbol=""
            echo -n "%{B$bblk} ${symbol} %{B-}"
        fi
    fi

	echo -e "%{B$nblk} $percent% %{B-}"
}

NET() {
	symbol="%{B$bblk}  %{B-}"
	disconnected=$(iw $interface link | awk '/Not/ {print $1}')

	ssid=$(
	if [ "$disconnected" = "Not" ]; then
		echo "NOT CONNECTED"
	else
		iw $interface link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//'
	fi)

	echo -n "${symbol}%{B$nblk} ${ssid} %{B-}"
}

DATE() {
    echo -n "%{B$bblk} %{F$fg}$(date "+%d/%m")%{F-} %{B-}"
}

CLOCK() {
    echo -n "%{B$hint}%{F$bg} $(date "+%H:%M") %{F-}%{B-}"
}

BAR() {
    #ADD ALL THE THINGS
    while true; do
		buf="$(WRK) $(MUSIC)%{c}%{r}$(VOL) $(BAT) $(NET) $(DATE) $(CLOCK)" 
		echo "$buf"	
        sleep 0.1
    done | lemonbar -f $glyph \
        -f "$font" \
        -F "$fg" \
        -B "$bg" \
        -u "$border" \
		-r "$border" \
		-R "$bg" \
        -g "1264x$height+0+0" | sh &
}

BAR > /dev/null
