#!/bin/bash
#BACKUP

CMD="rsync -rtv"
DEST="/run/media/$USER/external"

if [ -d "$DEST"  ]; then
	#MEDIA
	$CMD $HOME/documents/ $DEST/documents/
	$CMD $HOME/downloads/ $DEST/downloads/
	$CMD $HOME/images/ $DEST/images/
	$CMD $HOME/music/ $DEST/music/
	$CMD $HOME/videos/ $DEST/videos/
	#SCRIPTS
	$CMD $HOME/bin/ $DEST/bin/
	#LOOSE
	$CMD $HOME/tmp/arch_install_guide $DEST/loose_files/
	$CMD $HOME/src/2bwm/config.h $DEST/loose_files/
	$CMD $HOME/.git/ricing/resources $DEST/loose_files/
	$CMD $HOME/.git/nxll.github.io/index.html $DEST/loose_files/
	
	notify-send "BACKUP COMPLETE"
else
	notify-send "NO BACKUP DIRECTORY"
fi
