#!/usr/bin/bash
#dmwrap - dmenu wrapper

font="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"
nb="#21211F"
nf="#B8B9B4"
sb="#9AC70E"
sf="#21211F"
w="830"
h="18"
x="140"
y="5"
opt="-fn "$font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -w "$w" -h "$h" -x "$x" -y "$y""

dmenu $opt 
