#!/usr/bin/bash
#dmwrap - dmenu wrapper

font="-lucy-tewi-medium-r-normal--11-90-100-100-c-60-iso10646-1"
nb="#21211F"
nf="#B8B9B4"
sb="#5E5E5C"
sf="#21211F"
w="880"
h="18"
x="83"
y="5"
opt="-fn "$font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -w "$w" -h "$h" -x "$x" -y "$y""

dmenu $opt 
