#!/bin/bash
#BACKUP REPOS TO GITHUB

cph="cp -r $HOME"
dotfiles="$HOME/.git/dotfiles"
scripts="$HOME/.git/scripts"

case $1 in
-dotfiles)
	$cph/.zshrc $dotfiles/
	$cph/.vimrc $dotfiles/
	$cph/.interrobangrc $dotfiles/
	$cph/.tmux.conf $dotfiles/
	$cph/.xinitrc $dotfiles/
	$cph/.Xresources $dotfiles/
	$cph/.compton.conf $dotfiles/
	$cph/.zlogin $dotfiles/

	$cph/.vim/colors/fray.vim $dotfiles/.vim/colors/
	$cph/.ncmpcpp/config $dotfiles/.ncmpcpp/
	$cph/.weechat/weechat.conf $dotfiles/.weechat/

	$cph/.config/dunst/ $dotfiles/.config/
	$cph/.config/herbstluftwm/ $dotfiles/.config/
	rm -rf $HOME/.config/zenbu/__pycache__
	$cph/.config/zenbu/ $dotfiles/.config/
	$cph/.config/mpd/mpd.conf $dotfiles/.config/mpd/
	$cph/.config/mpv/ $dotfiles/.config/
	$cph/.config/zathura/ $dotfiles/.config/
	$cph/.config/vis/config $dotfiles/.config/vis/
	$cph/.config/vis/colors/mono.scheme $dotfiles/.config/vis/colors/
	$cph/.config/user-dirs.dirs $dotfiles/.config/

	#PUSH
	cd $dotfiles
	git add .
	git commit -m updates
	git push ghdots master
	git push tdots master
	notify-send "DOTFILES UP TO DATE"
	cd
	;;
-scripts)
	$cph/bin/* $scripts/

	#PUSH
	cd $scripts
	git add .
	git commit -m updates
	git push ghscripts master
	git push tscripts master
	notify-send "SCRIPTS UP TO DATE"
	cd
	;;
*) echo "You modified me to push -dotfiles or -scripts" ;;
esac
