#!/bin/sh
#
# z3bra - 2015 (c) wtfpl
# make the current window "rainbowish"... Awesome idea from xero@nixers.net !

FREQ=${FREQ:-0.3}
COLORS="80807E 949492 A8A8A6 949492 80807E"
CUR=$(pfw)

while :; do
    for c in $COLORS; do
        chwb -c $c $(pfw) 
        sleep $FREQ
    done
done
