#!/bin/sh
#
# z3bra - 2015 (c) wtfpl
# make the current window "rainbowish"... Awesome idea from xero@nixers.net !

FREQ=${FREQ:-0.1}
COLORS="6B6B69 757573 80807E 8A8A88 949492 9E9E9C A8A8A6 A8A8A6 9E9E9C 949492 8A8A88 80807E 757573 6B6B69"
CUR=$(pfw)

while :; do
    for c in $COLORS; do
        chwb -c $c $(pfw) 
        sleep $FREQ
    done
done
